//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgGroup.OnlineStore.Infrastructure.SampleData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Products {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Products() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgGroup.OnlineStore.Infrastructure.SampleData.Products", typeof(Products).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ProductID&quot;: 1,
        ///    &quot;ProductName&quot;: &quot;Chai&quot;,
        ///    &quot;UnitPrice&quot;: 18,
        ///    &quot;UnitsInStock&quot;: 39,
        ///    &quot;Discontinued&quot;: false
        ///  },
        ///  {
        ///    &quot;ProductID&quot;: 2,
        ///    &quot;ProductName&quot;: &quot;Chang&quot;,
        ///    &quot;UnitPrice&quot;: 19,
        ///    &quot;UnitsInStock&quot;: 17,
        ///    &quot;Discontinued&quot;: false
        ///  },
        ///  {
        ///    &quot;ProductID&quot;: 3,
        ///    &quot;ProductName&quot;: &quot;Aniseed Syrup&quot;,
        ///    &quot;UnitPrice&quot;: 10,
        ///    &quot;UnitsInStock&quot;: 13,
        ///    &quot;Discontinued&quot;: false
        ///  },
        ///  {
        ///    &quot;ProductID&quot;: 4,
        ///    &quot;ProductName&quot;: &quot;Chef Anton&apos;s Cajun Seasoning&quot;,
        ///    &quot;UnitPrice&quot;: 22,
        ///    &quot;UnitsInStock&quot;: 53, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductsCollectionJson {
            get {
                return ResourceManager.GetString("ProductsCollectionJson", resourceCulture);
            }
        }
    }
}
